versionVelocity=4.0.0-SNAPSHOT
versionVelocity34=3.4.0-SNAPSHOT

versionAdventure=4.26.1
versionNetty=4.1.118.Final
versionByteBuddy=1.17.5
versionJUnit=5.12.1

group=org.lime
overrideJavaVersion=21
javaCompilerVersion=25
org.gradle.java.installations.fromEnv=JAVA_HOME_25_X64
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
